version: "3"

tasks:
  openapi:
    cmds:
      - go run . -spec
      - npm run openapi-ts --prefix ./frontend
  sqlc:
    cmds:
      - sqlc generate
  frontend-dev:
    cmd: npm run dev --prefix ./frontend
    internal: true
  backend-dev:
    cmd: go run .
    internal: true
  dev:
    deps: [backend-dev, frontend-dev]
  
