// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package store

import (
	"time"

	"huma-app/store/types"
)

type User struct {
	ID        int64      `json:"id"`
	Email     string     `format:"email" json:"email" required:"true"`
	Password  string     `json:"password"`
	CreatedAt time.Time  `json:"created_at"`
	Role      types.Role `json:"role"`
}
